# copy pasted. you can change it
env:
  browser: true
  es6: true
  node: true
  webextensions: true
  jquery: true
globals:
  XRegExp: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2016
  sourceType: module
# These rules seem to generally follow the StandardJS style:
# https://standardjs.com/rules.html
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  camelcase:
    - error
  no-console: "warn"
