# Travis yml file taken some parts from https://github.com/travis-ci/travis-ci/issues/10118
sudo: required
language: python
python:
  - "3.6"
# command to install dependencies
cache: pip

before_install:
  - chmod -R 777 .

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - cd CreeDictionary
#  - python manage.py makemigrations
#  - python manage.py migrate
  - cd ../
  - cd DictionaryImporter
  - ./RunTest.sh