env: DEBUG=True
dist: xenial

after_success: codecov

cache:
  pip: true
  directories:
    - $HOME/.cache
    - node_modules # NPM packages

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - language: python

      install: pipenv install --dev

      python: "3.6"

      addons:
        apt:
          packages:
            - hfst

      script: pipenv run test --cov=CreeDictionary

    - language: node_js

      addons:
        apt:
          packages:
            - pipenv

      before_script: pipenv install

    - stage: deploy
      addons:
        apt:
          packages:
            - curl

      script:
        - openssl aes-256-cbc -K $encrypted_49b37942e026_key -iv $encrypted_49b37942e026_iv -in cree-dictionary.key.enc -out cree-dictionary.key -d
        - curl --fail -XPOST -dsecret=$(sudo cat cree-dictionary.key) sapir.artsrn.ualberta.ca/redeploy/cree-dictionary

      after_success: ""
