matrix:
    include:
      - dist: xenial
        sudo: required
        language: python
        python:
          - "3.7"
        cache: pip

        before_install:
          - chmod -R 777 .

        install:
          - pip install -r requirements.txt

        script:
          - pycodestyle . --exclude=./CreeDictionary/API/migrations/*.py,./env/
          - coverage run --source CreeDictionary/ CreeDictionary/manage.py test API
          - coverage report -m
          - cd DictionaryImporter
          - coverage run --source . -m unittest discover -p  "*_test.py"
          - coverage report -m

      - language: node_js
        node_js:
            - 10
        cache:
            npm: true
            directories:
            - ~/.cache
        install:
            - npm install
            - npm ci
            - npm run install:test
        script:
            - npm build
            - npm django & 
            - $(npm bin)/wait-on http://localhost:8000
            - npm run e2e:headless