env: DEBUG=True
dist: xenial

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
      - hfst

after_success: codecov

cache:
  pip: true
  directories:
    - $HOME/.cache
    - node_modules # NPM packages

stages:
  - test
  - name: deploy
    # note for PRs this is the base branch name :/
    if: branch = master

jobs:
  include:
    - name: "Unit Tests"
      language: python

      install: pipenv install --dev

      python: "3.6"

      script: pipenv run test --cov=CreeDictionary

    - name: "Integration Tests"
      # turns out it's harder to configure python with language: node_js
      # it's easier to configure node_js with language: python instead
      language: python
      python: "3.6"

      install:
        - pipenv install
        - npm ci

      script: npm test

    - stage: deploy
      addons:
        apt:
          packages:
            - curl

      script:
        - openssl aes-256-cbc -K $encrypted_49b37942e026_key -iv $encrypted_49b37942e026_iv -in cree-dictionary.key.enc -out cree-dictionary.key -d
        - curl -dsecret=$(sudo cat cree-dictionary.key) sapir.artsrn.ualberta.ca/redeploy/cree-dictionary
