env: Production=false
sudo: required
dist: xenial

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - language: python
      python: "3.7"

      before_install:
        - sudo apt-get -y install apache2-dev
        - sudo apt-get -y install hfst

      install: pipenv install --dev
      before_script: pipenv run make-migrations && pipenv run migrate
      script: pipenv run test --cov=CreeDictionary
      after_success: codecov

    - stage: deploy
      install: sudo apt-get -y install curl
      script:
        - openssl aes-256-cbc -K $encrypted_49b37942e026_key -iv $encrypted_49b37942e026_iv -in cree-dictionary.key.enc -out cree-dictionary.key -d
        - curl --fail -XPOST -dsecret=$(sudo cat cree-dictionary.key) sapir.artsrn.ualberta.ca/redeploy/cree-dictionary
