env:
  - Production=false
sudo: required
dist: xenial

stages:
  - test
  - name: deploy
    if: branch = master

branches:
  except:
    - broken

jobs:
  include:
    - language: python
      python:
          - "3.7"
      cache: pip

      before_install:
        - sudo apt-get -y install apache2-dev
        - sudo apt-get -y install hfst
        - chmod -R 777 .

      install:
          - pip install -r requirements.txt

      script:
          - coverage run --source CreeDictionary/ CreeDictionary/manage.py test API.tests
          - coverage report -m
          - cd DictionaryImporter
          - coverage run --source . -m unittest discover -p  "*_test.py"
          - coverage report -m

    - stage: deploy
      install: sudo apt-get -y install curl
      script:
        - openssl aes-256-cbc -K $encrypted_49b37942e026_key -iv $encrypted_49b37942e026_iv -in cree-dictionary.key.enc -out cree-dictionary.key -d
        - curl --fail -XPOST -dsecret=$(sudo cat cree-dictionary.key) sapir.artsrn.ualberta.ca/redeploy/cree-dictionary
