matrix:
    include:
      - dist: xenial
        sudo: required
        language: python
        python:
            - "3.7"
        cache: pip

        before_install:
            - chmod -R 777 .

        install:
            - pip install -r requirements.txt

        script:
            - pycodestyle . --exclude=./CreeDictionary/API/migrations/*.py,./env/
            - coverage run --source CreeDictionary/ CreeDictionary/manage.py test API
            - coverage report -m
            - cd DictionaryImporter
            - coverage run --source . -m unittest discover -p  "*_test.py"
            - coverage report -m

      - dist: xenial
        sudo: required
        language: node_js
        node_js:
            - 10
        cache:
            npm: true
            directories:
            - ~/.cache
        before_install:
            - sudo apt-get -y install python3-pip python3-setuptools python-dev
        install:
            - sudo -H pip3 install -r requirements.txt
            - npm ci
        script:
            - npm run build
            - npm run django3 & wait-on http://localhost:8000
            - npm run e2e:headless