# copy pasted. you can change it
env:
  browser: true
  es6: true
  node: true
  webextensions: true
  jquery: true
globals:
  XRegExp: true
  # Cypress/Mocha globals
  describe: true
  it: true
  beforeEach: true
  cy: true
  context: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2016
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: "warn"
