name: Update FST files

on: repository_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: remove old fomabins and hfstols
        run: |
          cd CreeDictionary/res/fst
          rm *.fomabin
          rm *.hfstol
      - name: Update fsts
        run: |
          cd CreeDictionary/res/fst
          curl -s https://api.github.com/repos/UAlbertaALTLab/plains-cree-fsts/releases/latest | grep "crk-descriptive-analyzer.fomabin" | cut -d: -f 2,3 | tr -d \" | tail -1 |wget -qi -
          curl -s https://api.github.com/repos/UAlbertaALTLab/plains-cree-fsts/releases/latest | grep "crk-descriptive-analyzer.hfstol" | cut -d: -f 2,3 | tr -d \" | tail -1 |wget -qi -
          curl -s https://api.github.com/repos/UAlbertaALTLab/plains-cree-fsts/releases/latest | grep "crk-normative-generator.hfstol" | cut -d: -f 2,3 | tr -d \" | tail -1 |wget -qi -
          curl -s https://api.github.com/repos/UAlbertaALTLab/plains-cree-fsts/releases/latest | grep "crk-strict-analyzer.hfstol" | cut -d: -f 2,3 | tr -d \" | tail -1 | wget -qi -
      - name: Authenticate github
        run: git remote set-url origin https://Madoshakalaka:${{ secrets.FST_UPDATE_TOKEN }}@github.com/UAlbertaALTLab/cree-intelligent-dictionary
      - name: Create and push a new branch
        run: |
          git config --global user.email "syan4@ualberta.ca"
          git config --global user.name "matt"
          git checkout -b new-fst-release-$(date +%s)
          git add .
          git commit -m "new fst release"
          git push -u origin new-fst-release-$(date +%s)

      - name: Submit a pull request
        run: |
          curl --fail -u "Madoshakalaka:${{ secrets.FST_UPDATE_TOKEN }}" -X POST https://api.github.com/repos/UAlbertaALTLab/cree-intelligent-dictionary/pulls \
          -H 'Accept: application/vnd.github.shadow-cat-preview+json' \
          --data '{"title": "new fst releases available","head":"new-fst-release-$(date +%s)","base": "master", "body":"this pull request is automated and triggered by new fst releases"}'