name: Update FST files under construction

on: repository_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: say the event type
        run: echo the event type is ${{ event_type }}$
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.